# Logging
wandb_log: true
wandb_project: 'daisy-300m-sweep'
wandb_run_name: '300m8192'
# Torch config
torch.coordinate_descent_tuning: false
# Pretraining configuration
train_shards: "data/fineweb-edu/edu_fineweb_train_*.bin"
target_tokens: 100_000_000
cooldown_frac: 0.0
learning_rate_schedule: linear_decay
learning_rate_floor: 0.3
training_sequence_length: 8_192
train_attention_window_len: 3456
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.95]
    eps: 1.0e-10
    weight_decay: 0.0
    fused: true
    params:
      - group: head_params
        lr: 0.008039944 # 0.003464
      - group: embed_params
        lr: 0.4019972 # 0.1732
      - group: scalar_params
        lr: 0.03014979 # 0.01299
  - type: Muon
    momentum: 0.95
    weight_decay: 0.0
    params:
      - group: hidden_matrix_params
        lr: 0.02
full_windows: true
# Gradient accumulation
grad_acc_steps: 8
# Evaluations
val_shards:
  - type: "fineweb-edu"
    path: "data/fineweb-edu/edu_fineweb_val_*.bin"
    target_tokens: 5_242_880
    sequence_length: 8_192
val_loss_every_tokens:     6_912_000
# Checkpoints
checkpoint_warmup_tokens:   0
checkpoint_per_n_tokens:     0
save_checkpoint: false
# Model Definition
model_spec: daisy_300m